/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  // sidebar: [
  //   {
  //     type: "category",
  //     label: "菜单自定义",
  //     // 默认点击导航到的位置
  //     link: {
  //       type: 'doc',
  //       id: '命令/md'
  //     },
  //     items: ["docusaurus/配置","命令/md", {
  //       type: 'link',
  //       label: '外部链接',
  //       href: 'http://www.baidu.com'
  //     },
  //     {
  //       type: 'link',
  //       label: '内部链接',
  //       href: '/blog'
  //     },
  //     {
  //       type: 'html',
  //       value: '<button type="button" class="btn btn-primary" style="background: orange">关注作者</button>',
  //     },
  //     {
  //       type: "category",
  //       label: "菜单自定义",
  //       items: ["docusaurus/配置","命令/md", {
  //         type: 'link',
  //         label: '外部链接',
  //         href: 'http://www.baidu.com'
  //       },
  //       {
  //         type: 'link',
  //         label: '内部链接',
  //         href: '/blog'
  //       },
  //       {
  //         type: 'html',
  //         value: '<button type="button" class="btn btn-primary" style="background: orange">关注作者</button>',
  //       }
  //     ],
  //     },
  //   ],
  //   },
  // ],
};

module.exports = sidebars;
